---
deployment:
  tasks:
    - export DEPLOYPATH=/home/justaynd/repositories/portfolio/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp global.js $DEPLOYPATH
    - /bin/cp -R imgs $DEPLOYPATH